#!/bin/sh

export LC_ALL=C

echo "Cleaning up..."
rm -rfv /usr/share/iserv/src/Stsbl/BillBoardBundle
cd share/
find -type f -exec rm -v /usr/share/iserv/{} \;
cd ../

echo "Creating base directory..."
mkdir -pv /usr/share/iserv/src/Stsbl/BillBoardBundle

echo "Creating directory structure..."
find src/ -type d -exec mkdir -pv "/usr/share/iserv/{}" \;
cd share/
find -type d -exec mkdir -pv "/usr/share/iserv/{}" \;
cd ../

echo "Coyping files..."
find src/ -type f -exec cp -v "{}" "/usr/share/iserv/{}" \;
cd share/
find -type f -exec cp -v "{}" "/usr/share/iserv/{}" \;
cd ../

echo "Copying privs..."
cp -rv priv/* /usr/share/iserv/priv/

echo "Copying db..."
cp -rv db/* /usr/share/iserv/priv/

echo "Copying iservchk scripts..."
cp -rv iservchk/* /usr/share/iserv/iconf/etc/iserv/chk.d/
