#!/bin/bash -ex

if [ "$3" != "" ]
then
 dir=$1
else
 dir=$(python -c "import os.path; print os.path.relpath('$1', './')")
fi
 origdir=$dir

if [ "$5" != "" ]
then
  dir=$(echo $dir | sed -e "s/$5\///g")
fi

if [ "$4" != "" ]
then
  dir="$4""$dir"
fi

cp -v /usr/share/iserv/$dir $2".collect"/$6$origdir
